name: CI Pipeline

on:
  push:
    branches: [ "**" ]        # Run on every commit to any branch
  pull_request:
    branches: [ "**" ]        # Run for PRs from any branch
  workflow_dispatch:

permissions: write-all

jobs:
  gradle_check:
    name: Gradle Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@main

      - name: Run Gradle Check
        run: cd ./java && ./gradlew check -x license -x pmdMain -x pmdTest -x checkstyleMain -x checkstyleTest -x spotlessJavaCheck -x test


  gradle_publish:
    name: Gradle Publish
    needs: [ gradle_check ]  # ✅ Run only after both succeed
    if: github.ref == 'refs/heads/master' && github.repository == 'flanglet/kanzi'  # ✅ Only for master branch of main repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@main

      - name: Publish with Gradle
        run: cd ./java && ./gradlew publish -x license -x pmdMain -x pmdTest -x checkstyleMain -x checkstyleTest -x spotlessJavaCheck -x test
        env:
          ossrhUsername: ${{ secrets.OSSRHUSERNAME }}
          ossrhPassword: ${{ secrets.OSSRHPASSWORD }}
